CREATE TABLE CATEGORIA_PRODUCTO (
    ID_CATEGORIA INTEGER PRIMARY KEY,
    NOMBRE       TEXT    NOT NULL
);


CREATE TABLE PRODUCTO (
    ID_PRODUCTO        INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE             TEXT    NOT NULL,
    ID_CATEGORIA       INTEGER CONSTRAINT PRODUCTO_CATEGORIA_FK REFERENCES CATEGORIA_PRODUCTO (ID_CATEGORIA) ON DELETE CASCADE
                                                                                                             ON UPDATE CASCADE,
    DESCRIPCION        TEXT,
    PRECIO_UNIDAD      NUMERIC DEFAULT (0),
    UDS_ALMACEN        INTEGER DEFAULT (0),
    IMAGEN_URL         TEXT,
    ACTIVO             INTEGER (1) DEFAULT (0),
    FECHA_CREADA       TEXT    NOT NULL,
    FECHA_MODIFICACION TEXT    NOT NULL
);

